name: test_linux_3_7
os: linux
language: python
env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - wget ${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda info -a
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda env update --name root --file binder/environment.yml
  - bash binder/postBuild
  - conda install -c conda-forge libsass jupytext sphinx
  - pip install git+https://github.com/ExecutableBookProject/jupyter-book 
script:
  - jupyter-book build book
