title: Pyiron Virtual Workshop 2020
author: Sudarsan Surendralal
logo: images/pyiron-logo.png
repository:
    url         : https://github.com/pmrv/pyiron-virtual-workshop-2020
exclude_patterns: ["story_so_far/*", "tutorials/ex*"]
