title: Pyiron Virtual Workshop 2020
author: Sudarsan Surendralal
logo: images/pyiron-logo.png

execute:
  execute_notebooks           : off

repository:
    url                       : https://github.com/pyiron/pyiron-virtual-workshop-2020
    path_to_book              : "book/"

launch_buttons:
  binderhub_url               : https://mybinder.org
