title: Pyiron Virtual Workshop 2020
author: Sudarsan Surendralal
logo: images/pyiron-logo.png
repository:
    url         : https://github.com/jan-janssen/pyiron-virtual-workshop-2020/book
launch_buttons:
  binderhub_url: "https://mybinder.org"
