title: Pyiron Virtual Workshop 2020
author: Sudarsan Surendralal
logo: images/pyiron-logo.png

repository:
    url                       : https://github.com/pyiron/pyiron-virtual-workshop-2020
    path_to_book              : "book/"
    
binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"
